name: Run sdk-swift

on:
  workflow_call:
    inputs:
      env:
        type: string
    secrets:
      SLACK_WEBHOOK:
        required: true

permissions: {}

jobs:
  integration:
    name: "sdk-swift"
    runs-on: macos-latest
    env:
      ENV: ${{ inputs.env }}
      RUNNER: "sdk-swift"
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1

      - name: Set xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Execute sdk-swift
        run: npm run integration -- --runner sdk-swift

      - name: Upload partial allure-results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: sdk-swift
          path: './tmp/sdk-swift'
