name: Manual swift

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    name: "test"
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch integration
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: hyperledger-identus/integration
          event-type: integration
          client-payload: '{"component": "sdk-swift", "version": "f63b8a97860415820a7106677d6e7af7cf0fde99" }'
