name: Manual

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    name: "test"
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch integration
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: hyperledger-identus/integration
          event-type: integration
          client-payload: '{"component": "sdk-ts", "version": "d950b5f8e5fb72696399a0c10937192213f06a09" }'
