name: Manual swift

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    name: "test"
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch integration
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: hyperledger-identus/integration
          event-type: integration
          client-payload: '{"component": "sdk-swift", "version": "16e9ebd30b215e0a36ee999a9a9b7961dfcdccc3" }'
