name: Manual

on:
  workflow_dispatch:

jobs:
  test:
    name: "test"
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch integration
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: hyperledger-identus/integration
          event-type: integration
          client-payload: '{"component": "cloud-agent", "version": "1.40.0" }'
